Patching Import Error
ImportError: import name 'ssh_brute_force' from partially initialized module 'app' (most likely due to a circular import). Included imports inside the functions so they can be initialized when the functions are called. This should address the order of operations.